import { Inter } from 'next/font/google'
import './globals.css'
import Footer from './shared/Footer'
import Navbar from './shared/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = { 
  title: 'Home page | all doctors in bangladesh',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`${inter.className} bg-gray-50`}>{children}</body>
    </html>
  )
}
